server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia-example
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer
      retries: 2
    consumer:
      client-id: academia-server-client
      enable-auto-commit: true
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.JsonSerializer

auth:
  header: Authorization
  token: Bearer secret_key


kafka:
  topics:
    notification: academia


