package com.example.DepartmentPassport.model.enums.department;

public enum AssistanceProfile {
    TRAUMATOLOGY_AND_ORTHOPEDICS,
    ONCOLOGY,
    ANESTHESIOLOGY_AND_RESUSCITATION,
    GENERAL_SURGERY,
    GYNECOLOGY,
    CARDIAC_SURGERY,
    RHEUMATOLOGY,
    THERAPY,
    UROLOGY,
    ENDOCRINOLOGY,
    ENDOCRINE_SURGERY,
    XRAY_VASCULAR_DIAGNOSTICS,
    GASTROENTEROLOGY,
    DERMATOLOGY,
    CARDIOLOGY,
    MAMMALOGY,
    NEUROLOGY,
    OTOLARYNGOLOGY,
    OPHTHALMOLOGY



}
